package com.liferay.reestrFermerov.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.reestrFermerov.model.Fermer;
import com.liferay.reestrFermerov.service.FermerLocalServiceUtil;

/**
 * The extended model base implementation for the Fermer service. Represents a row in the &quot;RR_Fermer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FermerImpl}.
 * </p>
 *
 * @author liza
 * @see FermerImpl
 * @see com.liferay.reestrFermerov.model.Fermer
 * @generated
 */
public abstract class FermerBaseImpl extends FermerModelImpl implements Fermer {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a fermer model instance should use the {@link Fermer} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            FermerLocalServiceUtil.addFermer(this);
        } else {
            FermerLocalServiceUtil.updateFermer(this);
        }
    }
}
