package com.liferay.reestrFermerov.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.reestrFermerov.model.Rayon;
import com.liferay.reestrFermerov.service.RayonLocalServiceUtil;

/**
 * The extended model base implementation for the Rayon service. Represents a row in the &quot;RR_Rayon&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RayonImpl}.
 * </p>
 *
 * @author liza
 * @see RayonImpl
 * @see com.liferay.reestrFermerov.model.Rayon
 * @generated
 */
public abstract class RayonBaseImpl extends RayonModelImpl implements Rayon {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a rayon model instance should use the {@link Rayon} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            RayonLocalServiceUtil.addRayon(this);
        } else {
            RayonLocalServiceUtil.updateRayon(this);
        }
    }
}
