package com.liferay.reestrFermerov.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Fermer service. Represents a row in the &quot;RR_Fermer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.reestrFermerov.model.impl.FermerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.reestrFermerov.model.impl.FermerImpl}.
 * </p>
 *
 * @author liza
 * @see Fermer
 * @see com.liferay.reestrFermerov.model.impl.FermerImpl
 * @see com.liferay.reestrFermerov.model.impl.FermerModelImpl
 * @generated
 */
public interface FermerModel extends BaseModel<Fermer> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a fermer model instance should use the {@link Fermer} interface instead.
     */

    /**
     * Returns the primary key of this fermer.
     *
     * @return the primary key of this fermer
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this fermer.
     *
     * @param primaryKey the primary key of this fermer
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the fermer ID of this fermer.
     *
     * @return the fermer ID of this fermer
     */
    public long getFermerId();

    /**
     * Sets the fermer ID of this fermer.
     *
     * @param fermerId the fermer ID of this fermer
     */
    public void setFermerId(long fermerId);

    /**
     * Returns the name of this fermer.
     *
     * @return the name of this fermer
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this fermer.
     *
     * @param name the name of this fermer
     */
    public void setName(String name);

    /**
     * Returns the pravo forma of this fermer.
     *
     * @return the pravo forma of this fermer
     */
    @AutoEscape
    public String getPravoForma();

    /**
     * Sets the pravo forma of this fermer.
     *
     * @param pravoForma the pravo forma of this fermer
     */
    public void setPravoForma(String pravoForma);

    /**
     * Returns the inn of this fermer.
     *
     * @return the inn of this fermer
     */
    @AutoEscape
    public String getInn();

    /**
     * Sets the inn of this fermer.
     *
     * @param inn the inn of this fermer
     */
    public void setInn(String inn);

    /**
     * Returns the kpp of this fermer.
     *
     * @return the kpp of this fermer
     */
    @AutoEscape
    public String getKpp();

    /**
     * Sets the kpp of this fermer.
     *
     * @param kpp the kpp of this fermer
     */
    public void setKpp(String kpp);

    /**
     * Returns the ogrn of this fermer.
     *
     * @return the ogrn of this fermer
     */
    @AutoEscape
    public String getOgrn();

    /**
     * Sets the ogrn of this fermer.
     *
     * @param ogrn the ogrn of this fermer
     */
    public void setOgrn(String ogrn);

    /**
     * Returns the rayon registration of this fermer.
     *
     * @return the rayon registration of this fermer
     */
    @AutoEscape
    public String getRayonRegistration();

    /**
     * Sets the rayon registration of this fermer.
     *
     * @param rayonRegistration the rayon registration of this fermer
     */
    public void setRayonRegistration(String rayonRegistration);

    /**
     * Returns the rayon posev pole of this fermer.
     *
     * @return the rayon posev pole of this fermer
     */
    @AutoEscape
    public String getRayonPosevPole();

    /**
     * Sets the rayon posev pole of this fermer.
     *
     * @param rayonPosevPole the rayon posev pole of this fermer
     */
    public void setRayonPosevPole(String rayonPosevPole);

    /**
     * Returns the date registration of this fermer.
     *
     * @return the date registration of this fermer
     */
    public Date getDateRegistration();

    /**
     * Sets the date registration of this fermer.
     *
     * @param dateRegistration the date registration of this fermer
     */
    public void setDateRegistration(Date dateRegistration);

    /**
     * Returns the archive status of this fermer.
     *
     * @return the archive status of this fermer
     */
    public boolean getArchiveStatus();

    /**
     * Returns <code>true</code> if this fermer is archive status.
     *
     * @return <code>true</code> if this fermer is archive status; <code>false</code> otherwise
     */
    public boolean isArchiveStatus();

    /**
     * Sets whether this fermer is archive status.
     *
     * @param archiveStatus the archive status of this fermer
     */
    public void setArchiveStatus(boolean archiveStatus);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.liferay.reestrFermerov.model.Fermer fermer);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.liferay.reestrFermerov.model.Fermer> toCacheModel();

    @Override
    public com.liferay.reestrFermerov.model.Fermer toEscapedModel();

    @Override
    public com.liferay.reestrFermerov.model.Fermer toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
